from decimal import Decimal

import pytest
from babel.numbers import get_currency_name

from pycents.currency import Currency
from pycents.exceptions import BackendConfigurationError, InvalidFormatSpecError
from pycents.formatting.babel import BabelFormatter
from pycents.formatting.formatspec import FormatSpec
from pycents.rounding import RoundingMode

locales = [
    "af",
    "af_NA",
    "af_ZA",
    "agq",
    "agq_CM",
    "ak",
    "ak_GH",
    "am",
    "am_ET",
    "ar",
    "ar_001",
    "ar_AE",
    "ar_BH",
    "ar_DJ",
    "ar_DZ",
    "ar_EG",
    "ar_EH",
    "ar_ER",
    "ar_IL",
    "ar_IQ",
    "ar_JO",
    "ar_KM",
    "ar_KW",
    "ar_LB",
    "ar_LY",
    "ar_MA",
    "ar_MR",
    "ar_OM",
    "ar_PS",
    "ar_QA",
    "ar_SA",
    "ar_SD",
    "ar_SO",
    "ar_SS",
    "ar_SY",
    "ar_TD",
    "ar_TN",
    "ar_YE",
    "as",
    "as_IN",
    "asa",
    "asa_TZ",
    "ast",
    "ast_ES",
    "az",
    "az_Cyrl",
    "az_Cyrl_AZ",
    "az_Latn",
    "az_Latn_AZ",
    "ba",
    "ba_RU",
    "bas",
    "bas_CM",
    "be",
    "be_BY",
    "bem",
    "bem_ZM",
    "bez",
    "bez_TZ",
    "bg",
    "bg_BG",
    "bgc",
    "bgc_IN",
    "bho",
    "bho_IN",
    "blo",
    "blo_BJ",
    "bm",
    "bm_ML",
    "bn",
    "bn_BD",
    "bn_IN",
    "bo",
    "bo_CN",
    "bo_IN",
    "br",
    "br_FR",
    "brx",
    "brx_IN",
    "bs",
    "bs_Cyrl",
    "bs_Cyrl_BA",
    "bs_Latn",
    "bs_Latn_BA",
    "ca",
    "ca_AD",
    "ca_ES",
    "ca_FR",
    "ca_IT",
    "ccp",
    "ccp_BD",
    "ccp_IN",
    "ce",
    "ce_RU",
    "ceb",
    "ceb_PH",
    "cgg",
    "cgg_UG",
    "chr",
    "chr_US",
    "ckb",
    "ckb_IQ",
    "ckb_IR",
    "cs",
    "cs_CZ",
    "csw",
    "csw_CA",
    "cv",
    "cv_RU",
    "cy",
    "cy_GB",
    "da",
    "da_DK",
    "da_GL",
    "dav",
    "dav_KE",
    "de",
    "de_AT",
    "de_BE",
    "de_CH",
    "de_DE",
    "de_IT",
    "de_LI",
    "de_LU",
    "dje",
    "dje_NE",
    "doi",
    "doi_IN",
    "dsb",
    "dsb_DE",
    "dua",
    "dua_CM",
    "dyo",
    "dyo_SN",
    "dz",
    "dz_BT",
    "ebu",
    "ebu_KE",
    "ee",
    "ee_GH",
    "ee_TG",
    "el",
    "el_CY",
    "el_GR",
    "en",
    "en_001",
    "en_150",
    "en_AE",
    "en_AG",
    "en_AI",
    "en_AS",
    "en_AT",
    "en_AU",
    "en_BB",
    "en_BE",
    "en_BI",
    "en_BM",
    "en_BS",
    "en_BW",
    "en_BZ",
    "en_CA",
    "en_CC",
    "en_CH",
    "en_CK",
    "en_CM",
    "en_CX",
    "en_CY",
    "en_CZ",
    "en_DE",
    "en_DG",
    "en_DK",
    "en_DM",
    "en_ER",
    "en_ES",
    "en_FI",
    "en_FJ",
    "en_FK",
    "en_FM",
    "en_FR",
    "en_GB",
    "en_GD",
    "en_GG",
    "en_GH",
    "en_GI",
    "en_GM",
    "en_GS",
    "en_GU",
    "en_GY",
    "en_HK",
    "en_HU",
    "en_ID",
    "en_IE",
    "en_IL",
    "en_IM",
    "en_IN",
    "en_IO",
    "en_IT",
    "en_JE",
    "en_JM",
    "en_KE",
    "en_KI",
    "en_KN",
    "en_KY",
    "en_LC",
    "en_LR",
    "en_LS",
    "en_MG",
    "en_MH",
    "en_MO",
    "en_MP",
    "en_MS",
    "en_MT",
    "en_MU",
    "en_MV",
    "en_MW",
    "en_MY",
    "en_NA",
    "en_NF",
    "en_NG",
    "en_NL",
    "en_NO",
    "en_NR",
    "en_NU",
    "en_NZ",
    "en_PG",
    "en_PH",
    "en_PK",
    "en_PL",
    "en_PN",
    "en_PR",
    "en_PT",
    "en_PW",
    "en_RO",
    "en_RW",
    "en_SB",
    "en_SC",
    "en_SD",
    "en_SE",
    "en_SG",
    "en_SH",
    "en_SI",
    "en_SK",
    "en_SL",
    "en_SS",
    "en_SX",
    "en_SZ",
    "en_TC",
    "en_TK",
    "en_TO",
    "en_TT",
    "en_TV",
    "en_TZ",
    "en_UG",
    "en_UM",
    "en_US",
    "en_US_POSIX",
    "en_VC",
    "en_VG",
    "en_VI",
    "en_VU",
    "en_WS",
    "en_ZA",
    "en_ZM",
    "en_ZW",
    "eo",
    "eo_001",
    "es",
    "es_419",
    "es_AR",
    "es_BO",
    "es_BR",
    "es_BZ",
    "es_CL",
    "es_CO",
    "es_CR",
    "es_CU",
    "es_DO",
    "es_EA",
    "es_EC",
    "es_ES",
    "es_GQ",
    "es_GT",
    "es_HN",
    "es_IC",
    "es_MX",
    "es_NI",
    "es_PA",
    "es_PE",
    "es_PH",
    "es_PR",
    "es_PY",
    "es_SV",
    "es_US",
    "es_UY",
    "es_VE",
    "et",
    "et_EE",
    "eu",
    "eu_ES",
    "ewo",
    "ewo_CM",
    "fa",
    "fa_AF",
    "fa_IR",
    "ff",
    "ff_Adlm",
    "ff_Adlm_BF",
    "ff_Adlm_CM",
    "ff_Adlm_GH",
    "ff_Adlm_GM",
    "ff_Adlm_GN",
    "ff_Adlm_GW",
    "ff_Adlm_LR",
    "ff_Adlm_MR",
    "ff_Adlm_NE",
    "ff_Adlm_NG",
    "ff_Adlm_SL",
    "ff_Adlm_SN",
    "ff_Latn",
    "ff_Latn_BF",
    "ff_Latn_CM",
    "ff_Latn_GH",
    "ff_Latn_GM",
    "ff_Latn_GN",
    "ff_Latn_GW",
    "ff_Latn_LR",
    "ff_Latn_MR",
    "ff_Latn_NE",
    "ff_Latn_NG",
    "ff_Latn_SL",
    "ff_Latn_SN",
    "fi",
    "fi_FI",
    "fil",
    "fil_PH",
    "fo",
    "fo_DK",
    "fo_FO",
    "fr",
    "fr_BE",
    "fr_BF",
    "fr_BI",
    "fr_BJ",
    "fr_BL",
    "fr_CA",
    "fr_CD",
    "fr_CF",
    "fr_CG",
    "fr_CH",
    "fr_CI",
    "fr_CM",
    "fr_DJ",
    "fr_DZ",
    "fr_FR",
    "fr_GA",
    "fr_GF",
    "fr_GN",
    "fr_GP",
    "fr_GQ",
    "fr_HT",
    "fr_KM",
    "fr_LU",
    "fr_MA",
    "fr_MC",
    "fr_MF",
    "fr_MG",
    "fr_ML",
    "fr_MQ",
    "fr_MR",
    "fr_MU",
    "fr_NC",
    "fr_NE",
    "fr_PF",
    "fr_PM",
    "fr_RE",
    "fr_RW",
    "fr_SC",
    "fr_SN",
    "fr_SY",
    "fr_TD",
    "fr_TG",
    "fr_TN",
    "fr_VU",
    "fr_WF",
    "fr_YT",
    "fur",
    "fur_IT",
    "fy",
    "fy_NL",
    "ga",
    "ga_GB",
    "ga_IE",
    "gaa",
    "gaa_GH",
    "gd",
    "gd_GB",
    "gl",
    "gl_ES",
    "gsw",
    "gsw_CH",
    "gsw_FR",
    "gsw_LI",
    "gu",
    "gu_IN",
    "guz",
    "guz_KE",
    "gv",
    "gv_IM",
    "ha",
    "ha_GH",
    "ha_NE",
    "ha_NG",
    "haw",
    "haw_US",
    "he",
    "he_IL",
    "hi",
    "hi_IN",
    "hi_Latn",
    "hi_Latn_IN",
    "hr",
    "hr_BA",
    "hr_HR",
    "hsb",
    "hsb_DE",
    "hu",
    "hu_HU",
    "hy",
    "hy_AM",
    "ia",
    "ia_001",
    "id",
    "id_ID",
    "ie",
    "ie_EE",
    "ig",
    "ig_NG",
    "ii",
    "ii_CN",
    "is",
    "is_IS",
    "it",
    "it_CH",
    "it_IT",
    "it_SM",
    "it_VA",
    "ja",
    "ja_JP",
    "jgo",
    "jgo_CM",
    "jmc",
    "jmc_TZ",
    "jv",
    "jv_ID",
    "ka",
    "ka_GE",
    "kab",
    "kab_DZ",
    "kam",
    "kam_KE",
    "kde",
    "kde_TZ",
    "kea",
    "kea_CV",
    "kgp",
    "kgp_BR",
    "khq",
    "khq_ML",
    "ki",
    "ki_KE",
    "kk",
    "kk_Arab",
    "kk_Arab_CN",
    "kk_Cyrl",
    "kk_Cyrl_KZ",
    "kk_KZ",
    "kkj",
    "kkj_CM",
    "kl",
    "kl_GL",
    "kln",
    "kln_KE",
    "km",
    "km_KH",
    "kn",
    "kn_IN",
    "ko",
    "ko_CN",
    "ko_KP",
    "ko_KR",
    "kok",
    "kok_Deva",
    "kok_Deva_IN",
    "kok_Latn",
    "kok_Latn_IN",
    "ks",
    "ks_Arab",
    "ks_Arab_IN",
    "ks_Deva",
    "ks_Deva_IN",
    "ksb",
    "ksb_TZ",
    "ksf",
    "ksf_CM",
    "ksh",
    "ksh_DE",
    "ku",
    "ku",
    "ku_TR",
    "ku_TR",
    "kw",
    "kw_GB",
    "kxv",
    "kxv_Deva",
    "kxv_Deva_IN",
    "kxv_Latn",
    "kxv_Latn_IN",
    "kxv_Orya",
    "kxv_Orya_IN",
    "kxv_Telu",
    "kxv_Telu_IN",
    "ky",
    "ky_KG",
    "lag",
    "lag_TZ",
    "lb",
    "lb_LU",
    "lg",
    "lg_UG",
    "lij",
    "lij_IT",
    "lkt",
    "lkt_US",
    "lmo",
    "lmo_IT",
    "ln",
    "ln_AO",
    "ln_CD",
    "ln_CF",
    "ln_CG",
    "lo",
    "lo_LA",
    "lrc",
    "lrc_IQ",
    "lrc_IR",
    "lt",
    "lt_LT",
    "lu",
    "lu_CD",
    "luo",
    "luo_KE",
    "luy",
    "luy_KE",
    "lv",
    "lv_LV",
    "mai",
    "mai_IN",
    "mas",
    "mas_KE",
    "mas_TZ",
    "mer",
    "mer_KE",
    "mfe",
    "mfe_MU",
    "mg",
    "mg_MG",
    "mgh",
    "mgh_MZ",
    "mgo",
    "mgo_CM",
    "mi",
    "mi_NZ",
    "mk",
    "mk_MK",
    "ml",
    "ml_IN",
    "mn",
    "mn_MN",
    "mni",
    "mni_Beng",
    "mni_Beng_IN",
    "mr",
    "mr_IN",
    "ms",
    "ms_BN",
    "ms_ID",
    "ms_MY",
    "ms_SG",
    "mt",
    "mt_MT",
    "mua",
    "mua_CM",
    "my",
    "my_MM",
    "mzn",
    "mzn_IR",
    "naq",
    "naq_NA",
    "nb",
    "nb_NO",
    "nb_SJ",
    "nd",
    "nd_ZW",
    "nds",
    "nds_DE",
    "nds_NL",
    "ne",
    "ne_IN",
    "ne_NP",
    "nl",
    "nl_AW",
    "nl_BE",
    "nl_BQ",
    "nl_CW",
    "nl_NL",
    "nl_SR",
    "nl_SX",
    "nmg",
    "nmg_CM",
    "nn",
    "nn_NO",
    "nnh",
    "nnh_CM",
    "no",
    "nqo",
    "nqo_GN",
    "nso",
    "nso_ZA",
    "nus",
    "nus_SS",
    "nyn",
    "nyn_UG",
    "oc",
    "oc_ES",
    "oc_FR",
    "om",
    "om_ET",
    "om_KE",
    "or",
    "or_IN",
    "os",
    "os_GE",
    "os_RU",
    "pa",
    "pa_Arab",
    "pa_Arab_PK",
    "pa_Guru",
    "pa_Guru_IN",
    "pcm",
    "pcm_NG",
    "pl",
    "pl_PL",
    "prg",
    "prg_PL",
    "ps",
    "ps_AF",
    "ps_PK",
    "pt",
    "pt_AO",
    "pt_BR",
    "pt_CH",
    "pt_CV",
    "pt_GQ",
    "pt_GW",
    "pt_LU",
    "pt_MO",
    "pt_MZ",
    "pt_PT",
    "pt_ST",
    "pt_TL",
    "qu",
    "qu_BO",
    "qu_EC",
    "qu_PE",
    "raj",
    "raj_IN",
    "rm",
    "rm_CH",
    "rn",
    "rn_BI",
    "ro",
    "ro_MD",
    "ro_RO",
    "rof",
    "rof_TZ",
    "ru",
    "ru_BY",
    "ru_KG",
    "ru_KZ",
    "ru_MD",
    "ru_RU",
    "ru_UA",
    "rw",
    "rw_RW",
    "rwk",
    "rwk_TZ",
    "sa",
    "sa_IN",
    "sah",
    "sah_RU",
    "saq",
    "saq_KE",
    "sat",
    "sat_Olck",
    "sat_Olck_IN",
    "sbp",
    "sbp_TZ",
    "sc",
    "sc_IT",
    "scn",
    "scn_IT",
    "sd",
    "sd_Arab",
    "sd_Arab_PK",
    "sd_Deva",
    "sd_Deva_IN",
    "se",
    "se_FI",
    "se_NO",
    "se_SE",
    "seh",
    "seh_MZ",
    "ses",
    "ses_ML",
    "sg",
    "sg_CF",
    "shi",
    "shi_Latn",
    "shi_Latn_MA",
    "shi_Tfng",
    "shi_Tfng_MA",
    "shn",
    "shn_MM",
    "shn_TH",
    "si",
    "si_LK",
    "sk",
    "sk_SK",
    "sl",
    "sl_SI",
    "smn",
    "smn_FI",
    "sn",
    "sn_ZW",
    "so",
    "so_DJ",
    "so_ET",
    "so_KE",
    "so_SO",
    "sq",
    "sq_AL",
    "sq_MK",
    "sq_XK",
    "sr",
    "sr_Cyrl",
    "sr_Cyrl_BA",
    "sr_Cyrl_ME",
    "sr_Cyrl_RS",
    "sr_Cyrl_XK",
    "sr_Latn",
    "sr_Latn_BA",
    "sr_Latn_ME",
    "sr_Latn_RS",
    "sr_Latn_XK",
    "st",
    "st_LS",
    "st_ZA",
    "su",
    "su_Latn",
    "su_Latn_ID",
    "sv",
    "sv_AX",
    "sv_FI",
    "sv_SE",
    "sw",
    "sw_CD",
    "sw_KE",
    "sw_TZ",
    "sw_UG",
    "syr",
    "syr_IQ",
    "syr_SY",
    "szl",
    "szl_PL",
    "ta",
    "ta_IN",
    "ta_LK",
    "ta_MY",
    "ta_SG",
    "te",
    "te_IN",
    "teo",
    "teo_KE",
    "teo_UG",
    "tg",
    "tg_TJ",
    "th",
    "th_TH",
    "ti",
    "ti_ER",
    "ti_ET",
    "tk",
    "tk_TM",
    "tn",
    "tn_BW",
    "tn_ZA",
    "to",
    "to_TO",
    "tok",
    "tok_001",
    "tr",
    "tr_CY",
    "tr_TR",
    "tt",
    "tt_RU",
    "twq",
    "twq_NE",
    "tyv",
    "tyv_RU",
    "tzm",
    "tzm_MA",
    "ug",
    "ug_CN",
    "uk",
    "uk_UA",
    "ur",
    "ur_IN",
    "ur_PK",
    "uz",
    "uz_Arab",
    "uz_Arab_AF",
    "uz_Cyrl",
    "uz_Cyrl_UZ",
    "uz_Latn",
    "uz_Latn_UZ",
    "vai",
    "vai_Latn",
    "vai_Latn_LR",
    "vai_Vaii",
    "vai_Vaii_LR",
    "vec",
    "vec_IT",
    "vi",
    "vi_VN",
    "vmw",
    "vmw_MZ",
    "vun",
    "vun_TZ",
    "wae",
    "wae_CH",
    "wo",
    "wo_SN",
    "xh",
    "xh_ZA",
    "xnr",
    "xnr_IN",
    "xog",
    "xog_UG",
    "yav",
    "yav_CM",
    "yi",
    "yi_UA",
    "yo",
    "yo_BJ",
    "yo_NG",
    "yrl",
    "yrl_BR",
    "yrl_CO",
    "yrl_VE",
    "yue",
    "yue_Hans",
    "yue_Hans_CN",
    "yue_Hant",
    "yue_Hant_CN",
    "yue_Hant_HK",
    "yue_Hant_MO",
    "za",
    "za_CN",
    "zgh",
    "zgh_MA",
    "zh",
    "zh_Hans",
    "zh_Hans_CN",
    "zh_Hans_HK",
    "zh_Hans_MO",
    "zh_Hans_MY",
    "zh_Hans_SG",
    "zh_Hant",
    "zh_Hant_HK",
    "zh_Hant_MO",
    "zh_Hant_MY",
    "zh_Hant_TW",
    "zu",
    "zu_ZA",
]


# This method is duplicated in two test files
# TODO move to other place
def indexof(text: str, substr: str):
    try:
        ind = text.index(substr)
        return ind
    except ValueError:
        return -1


class TestBabelFormatter:
    @pytest.fixture
    def babel_formatter(self):
        fmt = BabelFormatter("en_US")
        return fmt

    @pytest.fixture
    def usd(self):
        return Currency.from_code("USD")

    def test_init(self):
        _babel = BabelFormatter("en_US")
        assert _babel.locale == "en_US"
        assert _babel.numbering_system is None
        assert _babel._rounding == RoundingMode.HALF_EVEN
        assert _babel._default_spec == FormatSpec()

    def test_init_with_empty_local(self):
        _babel = BabelFormatter("")
        assert len(_babel.locale) > 0

    def test_locale_property(self, babel_formatter):
        assert babel_formatter.locale == "en_US"
        babel_formatter.locale = "fr_FR"
        assert babel_formatter.locale == "fr_FR"

    @pytest.mark.parametrize(
        "display, amount, expected",
        [
            ("hidden", Decimal("1234.56"), "1,234.56"),
            ("symbol", Decimal("12.9923"), "$12.9923"),
            ("iso", Decimal("1234.56"), "USD\xa01,234.56"),
            ("name", Decimal("1234.56"), "1,234.56 US dollars"),
        ],
    )
    def test_currency_display_widths(
        self, babel_formatter, display, amount, expected, usd
    ):
        spec = FormatSpec(ccy_display=display)
        result = babel_formatter.format(amount, usd, spec)
        assert result == expected

    def test_invalid_display_width_raises_error(self, babel_formatter, usd):
        spec = FormatSpec(ccy_display="invalid_type")  # type: ignore
        with pytest.raises(AssertionError):
            babel_formatter.format(Decimal("100"), usd, spec)

    def test_name_display_and_accounting_raises_error(self, babel_formatter, usd):
        spec = FormatSpec(ccy_display="name", accounting=True)
        with pytest.raises(
            InvalidFormatSpecError,
            match="Cannot display currency name while using accounting format.",
        ):
            babel_formatter.format(Decimal("-2.99"), usd, spec)

    def test_name_display_with_compact_format(self, babel_formatter, usd):
        spec = FormatSpec(ccy_display="name", compact=True)
        result = babel_formatter.format(Decimal("1222"), usd, spec)

        assert result == "1.2K US dollars"

    @pytest.mark.parametrize("display", ["symbol", "iso"])
    def test_formatter_rejects_combining_compact_and_accounting_formats(
        self, babel_formatter, usd, display
    ):
        spec = FormatSpec(accounting=True, compact=True, ccy_display=display)
        with pytest.raises(
            InvalidFormatSpecError,
            match="Cannot mix compact and accounting format display",
        ):
            babel_formatter.format(Decimal("2.99"), usd, spec)

    # Accounting Sign Tests

    @pytest.mark.parametrize(
        "amount, accounting, expected",
        [
            (Decimal("-1232.56"), False, "-1,232.56"),  # Standard Negative
            (Decimal("-1233.56"), True, "(1,233.56)"),  # Accounting Negative
            (Decimal("1234.56"), True, "1,234.56"),  # Accounting Positive (no parens)
        ],
    )
    def test_accounting_format(
        self, babel_formatter, amount, accounting, expected, usd
    ):
        spec = FormatSpec(accounting=accounting, ccy_display="hidden")
        result = babel_formatter.format(amount, usd, spec)
        assert result == expected

    # Compact Notation Tests

    @pytest.mark.parametrize(
        "amount, expected",
        [
            (Decimal("1500"), "USD\xa01.5K"),
            (Decimal("1500000"), "USD\xa01.5M"),
            (Decimal("1500000000"), "USD\xa01.5B"),
        ],
    )
    def test_compact_notation_positive(self, babel_formatter, amount, expected, usd):
        spec = FormatSpec(compact=True, ccy_display="iso")
        result = babel_formatter.format(amount, usd, spec)
        assert result == expected

    # Grouping Separators

    @pytest.mark.parametrize(
        "group_sep, expected",
        [
            (True, "1,234,567.89"),
            (False, "1234567.89"),
        ],
    )
    def test_group_separator(self, babel_formatter, group_sep, expected, usd):
        spec = FormatSpec(group_separator=group_sep, ccy_display="hidden")
        result = babel_formatter.format(Decimal("1234567.89"), usd, spec)
        assert result == expected

    @pytest.mark.parametrize(
        "trim, amount, expected",
        [
            (True, Decimal("225.50"), "$225.5"),
            (False, Decimal("225.50"), "$225.50"),
            (True, Decimal("225.12345000"), "$225.12345"),
        ],
    )
    def teste_trim_trailing_zeros(self, trim, amount, expected, usd, babel_formatter):

        result = babel_formatter.format(
            amount, usd, FormatSpec(trim_trailing_zeros=trim)
        )

        assert result == expected

    @pytest.mark.parametrize(
        "trim, precision, amount, expected",
        [
            (True, 1, Decimal("2130"), "$2.1K"),
            (True, 2, Decimal("2130"), "$2.13K"),
            (False, 3, Decimal("2130"), "$2.13K"),
            (False, 4, Decimal("2130"), "$2.13K"),
        ],
    )
    def teste_trim_trailing_zeros_in_compact_notation(
        self, trim, precision, amount, expected, usd, babel_formatter
    ):
        # Babel is trimming the insignificant zero by default
        # TODO find a workaround to force babel to respect
        # the compact precision when the trim_trailing_zeros option
        # is False. e.g if compact precision is 4,  Decimal("22550")
        # should be formatted as $2.2550K not $2.255K
        spec = FormatSpec(
            compact=True, compact_precision=precision, trim_trailing_zeros=trim
        )
        result = babel_formatter.format(amount, usd, spec)

        assert result == expected

    # Rounding Policies

    @pytest.mark.parametrize(
        "amount, display, rounding, expected",
        [
            (Decimal("12340"), "symbol", RoundingMode.DOWN, "$12.34K"),
            (Decimal("12345"), "hidden", RoundingMode.UP, "12.35K"),
            (
                Decimal("12345"),
                "iso",
                RoundingMode.HALF_EVEN,
                "USD\xa012.34K",
            ),
            (
                Decimal("12355"),
                "symbol",
                RoundingMode.HALF_EVEN,
                "$12.36K",
            ),
            (
                Decimal("12345"),
                "name",
                RoundingMode.HALF_UP,
                "12.35K US dollars",
            ),
        ],
    )
    def test_rounding_policies(
        self, babel_formatter, amount, display, rounding, expected, usd
    ):
        spec = FormatSpec(ccy_display=display, compact=True, compact_precision=2)
        babel_formatter.configure(rounding=rounding)
        result = babel_formatter.format(amount, usd, spec)
        assert result == expected

    def test_configure(self, babel_formatter):
        babel_formatter.configure(
            compact=True,
            compact_precision=3,
            accounting=True,
            group_separator=False,
            trim_trailing_zeros=True,
        )
        expected = FormatSpec(
            ccy_display="symbol",
            compact=True,
            compact_precision=3,
            accounting=True,
            group_separator=False,
            trim_trailing_zeros=True,
        )

        assert babel_formatter._default_spec == expected

    def test_system_numbering(self, babel_formatter, usd):
        babel_formatter.locale = "en_US"
        result = babel_formatter.format(Decimal("1099.98"), usd, FormatSpec())
        assert result == "$1,099.98"

        babel_formatter.locale = "ar_EG"
        babel_formatter.numbering_system = "default"
        result = babel_formatter.format(Decimal("1099.98"), usd, FormatSpec())
        assert result == "\u200f1٬099٫98\xa0US$"

    def test_formatter_rejects_invalid_numbering_system(self, babel_formatter, usd):
        babel_formatter.numbering_system = "xxx"
        with pytest.raises(
            BackendConfigurationError,
            match=r"^Numbering system 'xxx' is not supported",
        ):
            babel_formatter.format(Decimal("2"), usd, FormatSpec())

    @pytest.mark.parametrize(
        "display",
        [
            "symbol",
            "iso",
            "hidden",
        ],
    )
    @pytest.mark.slow
    def test_custom_currency_formatting(self, display):
        for locale in locales:
            babel_fmt = BabelFormatter(str(locale))
            eur = babel_fmt.format(
                Decimal("2999213"),
                Currency.from_code("EUR"),
                FormatSpec(ccy_display=display),
            )

            tst = babel_fmt.format(
                Decimal("2999213"),
                Currency.from_code("TST"),
                FormatSpec(ccy_display=display),
            )

            str_eur = eur.replace("EUR", "").replace("€", "")
            str_tst = tst.replace("TST", "").replace("¤", "")
            assert str_eur == str_tst, f"{locale}"

    @pytest.mark.slow
    def test_custom_currency_formatting_long_name(self):
        for locale in locales:
            babel_fmt = BabelFormatter(locale)
            eur = babel_fmt.format(
                Decimal("2999213"),
                Currency.from_code("EUR"),
                FormatSpec(ccy_display="name"),
            )

            tst = babel_fmt.format(
                Decimal("2999213"),
                Currency.from_code("TST"),
                FormatSpec(ccy_display="name"),
            )

            assert indexof(tst, "¤") == indexof(eur, "€")

            name = get_currency_name(
                "EUR",
                Decimal("2999213"),
                str(locale),
            )

            assert indexof(tst, "test coin") == indexof(eur, name)
            tst_s = tst.replace("test coin", "").replace("¤", "").strip()
            eur_s = eur.replace(name, "").replace("€", "").strip()

            assert tst_s == eur_s
