import xml.etree.ElementTree as ET
from pathlib import Path

from download_xml import download_xml
from utils import _compute_hash, _get_stored_hash

_LIST_ONE_XML_TAGS = {
    "Ccy": "alphabetic_code",
    "CcyNm": "currency_name",
    "CcyMnrUnts": "minor_unit",
    "CcyNbr": "numeric_code",
}


def _get_element_text(element: ET.Element[str], target: str) -> str | int:
    elm = element.find(target)
    text = str(elm.text) if elm is not None else "None"
    if text == "N.A.":
        return 0
    try:
        value = int(text)
        return value
    except ValueError:
        return text


current_dir = Path(__file__).parent
root_dir = current_dir.parent

XML_PATH = current_dir / "list-one.xml"
OUTPUT_PATH = root_dir / "src/pycents/iso4217.py"


class EnumGen:
    def __init__(self, xml_path: Path = XML_PATH, output_path: Path = OUTPUT_PATH):
        self.xml_path = xml_path
        self.output_path = output_path

    def __enter__(self):
        download_xml()
        self.current_hash = _compute_hash(self.xml_path)
        self.last_hash = (
            _get_stored_hash(self.output_path) if self.output_path.exists() else None
        )
        return self

    def generate(self):
        if self.current_hash == self.last_hash:
            print("No changes detected in the XML data.")
            return
        tree = ET.parse(self.xml_path)
        root = tree.getroot()

        with open(self.output_path, "w", encoding="utf-8") as file:
            file.write("# WARNING: AUTO-GENERATED FILE\n")
            file.write("# This file was generated by the ISO 4217 download script.\n")
            file.write(
                "# DO NOT EDIT THIS FILE MANUALLY. ANY CHANGES MAY BE OVERWRITTEN.\n\n"
            )
            file.write("from enum import Enum\n\n")
            file.write(f'_xml_hash = "{self.current_hash}"\n\n')
            file.write("class Ccy(Enum):\n")
            _code_seen = set()
            for entry in root.findall("./CcyTbl/CcyNtry"):
                first, *last = _LIST_ONE_XML_TAGS.keys()
                alphabetic_code = _get_element_text(entry, first)
                if alphabetic_code == "None" or alphabetic_code in _code_seen:
                    continue
                _code_seen.add(alphabetic_code)
                dump = f'    {alphabetic_code} = ("{alphabetic_code}"'
                for key in last:
                    _val = _get_element_text(entry, key)
                    if isinstance(_val, int):
                        _val = int(_val)
                    else:
                        _val = f'"{_val}"'
                    dump += f", {_val}"
                dump += ")\n"
                file.write(dump)
            file.write("\n")
            attrs = _LIST_ONE_XML_TAGS.values()
            file.write(f"    def __init__(self, {', '.join(attrs)}):\n")
            for attr in attrs:
                file.write(f"        self.{attr} = {attr}\n")

            print("Successfully generated currencies enum!")

    def __exit__(self, exc_type, exc_value, traceback):
        self.xml_path.unlink(missing_ok=True)
        return False


if __name__ == "__main__":
    with EnumGen() as gn:
        gn.generate()
